[package]
name = "rsa"
version = "0.1.0"
authors = ["Hiroyuki Miyazaki <miyazaki@mcommit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.15" # Or a newer version
